### ISSUE TITLE
Not compatible with Flutter 3.3

### ISSUE THREAD

**Issue by a-v-ebrahimi** [akbarpulatov/flutter_awesome_select#45]
When I try to run on Flutter 3.3, I receive these errors:

```
awesome_select-5.2.0/lib/src/widget.dart:1122:66: Error: The getter 'cursorColor' isn't defined for the class 'ThemeData'.
awesome_select-5.2.0/lib/src/widget.dart:1185:20: Error: The getter 'FlatButton' isn't defined for the class 'S2State<T>'.

```

**Comment by pavel604** [comment]
It appears that the plugin is not maintained. The short handsolution is to copy the plugin from `.pub-cache` folder to your project dir and address the issue yourself:
```yaml
# pubspec.yaml
awesome_select:
    path: ./path/to/awesome_select
```
