### ISSUE TITLE
SmartSelect.single without an initial value

### ISSUE THREAD

**Issue by oravecz** [akbarpulatov/flutter_awesome_select#49]
How do I create a SmartSelect component when the user has not yet made a selection?

`selectedValue` is not nullable and is required.

```dart
SmartSelect<T>.single(
    selectedValue: blocState.selectedValue,  // blocState.selectedValue can be null
    ...
)
```

**Comment by mauriziopinotti** [comment]
I have created a pull request here: https://github.com/akbarpulatov/flutter_awesome_select/pull/58

If anyone wants to use it before a new release is available on pub.dev (looks like this project is unmaintained now) it can be done by overriding the dependency with

```yaml
  awesome_select:
    git:
      url: https://github.com/easyhour/flutter_awesome_select/
      ref: master
```
